export const commonStyles = (theme) => ({
	heroText: {
		"&.MuiTypography-root": {
			fontFamily: "Solway",
			fontSize: "40px",
			color: "#FFF",
			fontWeight: "400",
		},
		width: "388px",
	},
	heroSection: {
		position: "relative",
		width: "95%",
		height: "480px",
		aspectRatio: "auto",
		maxWidth: "1464px",
		display: "flex",
		alignItems: "center",
		borderRadius: "50px",
	},
	textWrapper: {
		objectFit: "cover",
		position: "absolute",
		display: "flex",
		alignItems: "center",
		padding: "0 72px",
		height: "100%",
		width: "100%",
		background:
			"linear-gradient(90deg, rgba(0, 0, 0, 0.8) 10%, rgba(0, 0, 0, 0) 100%)",
		borderRadius: "10px",
	},
	whoWeAreSection: {
		"&.MuiPaper-root": {
			width: "95%",
			maxWidth: "1464px",
			height: "409px",
			backgroundColor: "#F1F1F1",
			display: "flex",
			alignItems: "center",
			padding: "30px ",
			gap: "30px",
		},
	},
	whoWeAreText: {
		height: "100%",
		width: "100%",
		maxWidth: "708px",
		display: "flex",
		flexDirection: "column",
		justifyContent: "center",
		alignItems: "flex-start",
	},
	whoWeAreTextHeader: {
		"&.MuiTypography-root": {
			marginBottom: "10px",
			fontSize: "28px",
			fontWeight: "600",
			lineHeight: "38px",
		},
	},
	whoWeAreTextDescription: {
		width: "100%",
		"&.MuiTypography-root": {
			color: "#1A1A1A",
			lineHeight: "24px",
			fontSize: "18px",
			opacity: "0.6",
			color: "#1A1A1A",
			maxHeight: "196px",
			overflow: "hidden",
			textOverflow: "ellipsis",
		},
	},
	whoWeAreImg: {
		objectFit: "cover",
		width: "50%",
		height: "100%",
		maxWidth: "660px",
	},
	whoWeAreButton: {
		width: "30%",
		height: "64px",
		"&.MuiButton-root": {
			fontWeight: "600",
			marginTop: "10px",
			fontSize: "18px",
			color: "#002550",
			textTransform: "none",
			borderColor: "#002550",
		},
	},
	offeringsSection: {
		width: "100%",
		maxWidth: "1464px",
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
	},
	sectionTitle: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		padding: "0 0 10px 0",
		"&.MuiTypography-root": {
			fontSize: "32px",
			fontWeight: "700",
			color: "#002550",
			lineHeight: "33px",
		},
	},
	offeringsHr: {
		width: "200px",
		height: "5px",
		backgroundColor: "#002550",
		textAlign: "center",
	},
	linkHighlighted: {
		textDecoration: "none",
		fontSize: "16px",
		fontWeight: "700",
		color: "#002550",
	},
	sectionDescription: {
		"&.MuiTypography-root": {
			marginTop: "20px",
			fontSize: "16px",
			marginBottom: "35px",
		},
	},
	tabsWrapper: {
		width: "100%",
		display: "flex",
		justifyContent: "center",
		gap: "30px",
		borderRadius: "2.5px",
	},
	tab: {
		position: "relative",
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
		width: "30%",
		maxWidth: "470px",
		height: "100px",
		backgroundColor: "#F2F4F6",
		cursor: "pointer",
	},
	tabNumber: {
		width: "48px",
		height: "48px",
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		borderRadius: "100%",
		backgroundColor: "#fff",
		fontSize: "24px",
		fontFamily: "Open Sans",
		lineHeight: "32px",
		marginRight: "10px",
	},
	tabTitle: {
		maxWidth: "199px",
		"&.MuiTypography-root": {
			fontSize: "24px",
			fontWeight: "400",
			lineHeight: "32px",
		},
	},
	activeTab: {
		backgroundColor: "#CCD3DC",
	},
	hrTab: {
		position: "absolute",
		bottom: 0,
		width: "100%",
		height: "5px",
		backgroundColor: "#002550",
	},
	cardsWrapper: {
		width: "100%",
		display: "flex",
		gap: "24px",
		marginTop: "35px",
		justifyContent: "center",
	},
	card: {
		width: "100%",
		height: "680px",
		maxWidth: "456px",
		padding: "30px 24px",
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		"&:hover": {
			boxShadow: "0px 0px 10px rgba(0, 0, 0, 0.25)",
		},
	},
	contentWrapper: {
		"&.MuiCardContent-root": {
			marginTop: "30px",
			width: "100%",
			padding: 0,
			flexGrow: 1,
		},
	},
	cardTitle: {
		"&.MuiTypography-root": {
			fontSize: "28px",
			fontWeight: "600",
			marginBottom: "22px",
		},
	},
	cardDescription: {
		"&.MuiTypography-root": {
			fontSize: "18px",
			fontWeight: "400",
			lineHeight: "24px",
			color: "#1A1A1A",
			opacity: "0.6",
		},
	},
	cardActions: {
		"&.MuiCardActions-root": {
			margin: 0,
			padding: 0,
			alignSelf: "flex-start",
		},
	},
	cardButton: {
		height: "64px",
		"&.MuiButton-root": {
			fontWeight: "600",
			padding: "0px 40px",
			marginTop: "10px",
			fontSize: "18px",
			color: "#002550",
			textTransform: "none",
			borderColor: "#002550",
		},
	},
	ourTeamBlogs: {
		width: "100%",
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		backgroundColor: "#F2F4F6",
		paddingTop: "35px",
		paddingBottom: "35px",
		gap: "70px",
	},
	titleContainer: {
		width: "100%",
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
	},
	ourTeamHr: {
		width: "54px",
		height: "5px",
		backgroundColor: "#002550",
	},
	ourTeamCardsWrapper: {
		width: "100%",
		maxWidth: "1464px",
		display: "flex",
		gap: "46px",
		marginTop: "35px",
		justifyContent: "center",
	},
	ourTeamCard: {
		width: "100%",
		height: "680px",
		maxWidth: "456px",
		padding: "30px 24px",
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		"&:hover": {
			boxShadow: "0px 0px 10px rgba(0, 0, 0, 0.25)",
		},
	},
	nameAndRole: {
		display: "flex",
		justifyContent: "space-between",
		height: "40px",
		alignItems: "center",
		marginBottom: "22px",
	},
	cardRole: {
		"&.MuiTypography-root": {
			fontSize: "24px",
			color: "#1A1A1A",
			opacity: "0.6",
			fontWeight: "600",
		},
	},
	ourTeamCardTitle: {
		"&.MuiTypography-root": {
			fontSize: "28px",
			fontWeight: "600",
		},
	},
	ourTeamCardDescription: {
		"&.MuiTypography-root": {
			fontSize: "16px",
			fontWeight: "400",
			lineHeight: "22px",
			color: "#1A1A1A",
			opacity: "0.6",
		},
	},
})
